language: node_js
node_js: 8
script: yarn build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: FRdGe9I92IzTDsQLiWwzuf5uYoH/zYUcKp0Co8AVBE4QT/aUSQ6jSKcVt+pNm2fyBKEeEVEqqnvBWsrDdgGzoLO+wixpJQYuaTL4uPtQwxwnbKLdTfabg7rRkbjJr9W8bcKYKHim+rPcSjEW/vCOrEnSBrfOfH1I1wXcv8F8YMgLBu/db0Ibvd/zd/4WFDMrWG9LcZEHunm2Ee0USJv9R6sNjcE0O6KlM0hEdnNc6XxdEuqTZJ6UQaEoGTzh3HiaeLO3MlVyxCCev9/4VyHbtr0d+ti2J7esmdxfRUxw7qfUbZiqCgxsykT4HEt+rRmncUj503wsKlOTrLvQT6RmmiHXMvgrOtpHbw+E8Zp05sEtEz8ezJKHKRN71+eTY9QsvF8DkjsKrgyumreuXmNS+MsTNrRVk9LJWYHS8NXdzjMLs6mZVXD2xzaHAlPRnRGx3sMthxJGEfBp8IXrQRgMmbr+Sf93eXE0JKYAhCHYTwo7G528/OK+4OMctFuGDUrXtUJwHTSgWqJ4W3EElVGWU4D1xgsWqzQO7/Gjy1EXkX7e3vPERZ7idVmiGnV+5VI+/ztfx1jF2RRV2sMYpTFrb8zN3hAee3EJAbnME/e5coCEY76I1qkiw5N5l+VKIsgZHTrycBZ6O+mRzuGFekQ8ocU43671SNMj4uRL8ygcWpw=
