language: node_js
node_js: 8
script: yarn build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: YJcz3WxP5nP9Far7UaRVR1kcJKYIq5Qm8nJxTXuj/+bm0TKttyEUYoJDnaM5FBDJVDglnPs6yZVhoambzVDsRW+BhbATY3oO5itudptr6+DunKFvD3CWZ58KWaCKsGbuE3NptjeFip4jjFkvD2EdBmMcu2AiZcvhC2VZVxXMzpZjhXYLSmx2qTclf8DG4ba+eCpri6fPOen6t9c3EV8xmP7qsShJFwPfsehi3YU76KvenuokJ4RFVwRiuL8JiMcPa1favZh0xqVz5qMOQEm0O7CBzDBFEhRBnTyohGrSTWRACUUej8BJdykAvJGw5EH+xwDa+fy17lxGC3Sh8zcLWoxaY73zC7saG+y109uWQu2BbYkvSmLwi3Pm78Vh5edfFqFR4zCwQvPx7m1ISRqzFQ9SImL/H6KKQ/nDbuuBWF9tyN4wYj9M1ZWzOOXpwIJkwAHGCa/4BV29gAG/3h/BS2Ki5d1XoyKQSGiNAUai31L0EeSvzmh7RG2Ulj13tx6EPkNZpTFSt2Ek5jALWK+aYDtStLLS/KV/OLZ36dxdhE3W1ZutCnLqTlIg87gRxnM2IxEpS/j1ZO5nGiBqTEIAxOz3TReRN8GuL22j7eCjjKkwFQJ8/i0VoE5LmMTCtxy01zgcEfiU8Lh4VJmQY79HPs9jeuA++Pvspb7YR/2S1FI=
