language: node_js
node_js: 8
before_install: 'npm i -g firebase-tools'
script: npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "gr5OLZ/TqdhviFM+3Snl3o7335Y5eClEKpzK6DhbYzlO9Ppx+OqsqhqkQnfxYXcD2eCnDXnKtghWbiKqlIFIpfaBYratQr5bcU7ORFAhuKrs+87YgwZawlAvCPdUVs0ENy8QkkWzOMKFoYAuYRD80wZVSz3lyeW4COqEEXAzwN3PIx70oUWivTfQadDUXJs1Ao3UdPmU1shrk725EFEx+y0rEau5kCUjTBURob9OUqSekklFVtM4k103FTV+cW27uJAz0TRET/Y07754Q6vv1v7eDauDfQ7vgrqm8lRqropIDypC9PZCMCMyUKNl+cLbRJdLEU3Q0A5IgpMbRddsbtqu2a2XZ5o5yYf++C65ycSZKC/SMS58AyRqXTZXHG1CMtZcdis5jsP63oeIOIQhFO6Qzyc/r3p1cBVGN6H/CgXgk+hWFFxFUnFCCbubmxyCRlUb3hZulJPl1Rxy/9fst11gqeDoJjTXJzYCnZTTaaLAQFtyNbQ6nACXRHyAkXz7P2GyuFkWgN5c3g9GN++/RAFJTqMD1Oxe9xWPkb4Ahg8DXmovFlhEUkfpdfsyGBNfFqGrWZl7qJqSMf7S1EnGUtYKh4OyYromPXDfZ1pPWikoiwWtZb37PHNKGFiBSnTJXnJ9AFRKkSpMU7g6pGDGaNgKniWsiO/OaJAuQtu+qTg="
