language: node_js
node_js: 8
script: yarn build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: Pi0qV1HKobofxyHrWka0hY3o6/vPQjPaIb1pWCUn137Of48i84PIclnFwGafS4MhTGOj3Gsh/kRmz7KVPBO5zc7ZKXW1MpLlyXXEo7vda3QISw3LBQjU0iIgOFBzmXbuyRk3qBh7B2+tTZpv/LMwP8Qr1JEnP2WU/Bopxr1E9pRmZ/GdGefj8YSrtnTZ0vVgxdyzDlWi8qkLn514nN++7FaL0Q4lcw/3C7PKA/rhIJCpeYpaMKndj0LvvEcLuPSn6boGGqItHD5/MLWzS3/+fZCFVK4VccmUNMRGGbx0RhsSRJHULkIY2HBNdjWb9UgDRLEWL90RaFS8MIaDhdLlJqKHrZRhKl6tmI3uGB/oM8hd7PaKldvSDtOD/YnoOKjDMdwZKg4tKaF+GQx42Tse9/s9btNcguLrhuToMD57YWs34GKUCIEZ5IG+3MjdU5XTl4u22SVFse0ckl8zJRJ+CYeDsS2hx4v49ysQ6f5LhdrP9DBL8CHHuqH3EPH3qywl+WRohz5ZU0uDjpVhtJzaxfIEzq7HGHRJ9mcnVcRexasIxV3SPCMQKrKnZ2cinYeJTa3FtQi3Lr5QWJAgs6i2B/aTwIl1Lw82BsaBVRlIMg+tH/f7o+JPsyfSJRn4Eg15HBiueRQ+5B/RkQJKdNlfqcR/hTddEXsIDkYObjSENA0=
